# syntax=docker/dockerfile:1

FROM debian:latest

RUN <<-"EOF"
  set -euxo pipefail
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    latexmk \
    make \
    texlive \
    texlive-fonts-extra \
    texlive-latex-extra
  apt-get autoremove -y --purge
  rm -rf /var/lib/apt/lists/*
EOF
